# Madthreading Travis CI file

language: python

python:
  - "3.6"

# The apt packages here install our compiled code dependencies.
jobs:
  fast_finish: true
  include:
    # GCC 4.9
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - build-essential
            - cmake
            - clang-tidy
            - lcov
      env:
        - CC=gcc-4.9
        - CXX=g++-4.9
        - EXTRA_ARGS="--coverage --num-tasks=64"
    # GCC 5
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - build-essential
            - cmake
            - clang-tidy
      env:
        - CC=gcc-5
        - CXX=g++-5
        - EXTRA_ARGS="--num-tasks=256 --pyctest-build-type=RelWithDebInfo --tbb"
    # GCC 6
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - build-essential
            - cmake
            - clang-tidy
      env:
        - CC=gcc-6
        - CXX=g++-6
        - EXTRA_ARGS="--num-tasks=256 --pyctest-build-type=RelWithDebInfo --tbb"
    # GCC 7
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - gcc-7
            - g++-7
            - build-essential
            - cmake
            - clang-tidy
      env:
        - CC=gcc-7
        - CXX=g++-7
        - EXTRA_ARGS="--num-tasks=256 --pyctest-build-type=RelWithDebInfo --tbb"
    # Clang 5.0
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - clang++-5.0
            - build-essential
            - cmake
            - clang-tidy
      env:
        - CC=clang-5.0
        - CXX=clang++-5.0
        - EXTRA_ARGS="--num-tasks=256 --pyctest-build-type=RelWithDebInfo"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

install:
  - env
  - conda create -c defaults -c conda-forge -n pyctest python=3.6 pyctest tbb tbb-devel
  - source activate
  - conda activate pyctest

script:
  - export CMAKE_PREFIX_PATH="${CONDA_PREFIX}:${CMAKE_PREFIX_PATH}"
  - SOURCE_DIR=${PWD}
  - python ./pyctest-runner.py -SF --pyctest-model=Continuous --pyctest-site=Travis --static-analysis ${EXTRA_ARGS} -- -VV ${CTEST_ARGS} -- ${CMAKE_ARGS};
  - cd build-PTL
  - cmake -DCMAKE_INSTALL_PREFIX=${HOME}/ptl-install ${SOURCE_DIR}
  - cmake --build . --target install
  - mkdir -p ${HOME}/ptl-examples-build
  - cd ${HOME}/ptl-examples-build
  - CMAKE_PREFIX_PATH=${HOME}/ptl-install:${CMAKE_PREFIX_PATH} cmake ${SOURCE_DIR}/examples/basic
  - cmake --build . --target all
